### ISSUE TITLE
How to converte 300W-LP annotations to t7 format?

### ISSUE THREAD

**Issue by tjussh** [1adrianb/face-alignment-training#5]
hi @1adrianb , when I use your landmarks of t7 format, I got an error like 
"cannot open <../HELEN/HELEN 2469551410_1_8.t7> in mode r at torch/lib/TH/THDiskFile.c:673".
I think maye it's a format issue. So could you  please tell me how to converte 300W-LP annotations to t7 format?
thank you very much!

**Comment by ChooJinHe** [comment]
Hi @tjussh I have this issue too. Did you manage to solve it?

**Comment by 1adrianb** [comment]
Hi @ChooJinHe are you on Windows or linux?

**Comment by ChooJinHe** [comment]
Hi Adrian,


Thank you for sharing your amazing codes on GitHub. I am using Linux Ubuntu.


Many thanks,

Jin He


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by 1adrianb** [comment]
Can you please check if you have the latest version of torch? If this still doesnt fix it, I will convert them to .txt over the weekend to avoid future issues.

**Comment by ChooJinHe** [comment]
Hi Adrian,

I believe I am using the latest Torch version since I had reinstalled it 2 months ago. I will check the version on Monday. Thank you.

Best Regard,
Jin He


On Mar 2, 2018 5:53 PM, Adrian Bulat <notifications@github.com> wrote:

Can you please check if you have the latest version of torch? If this still doesnt fix it, I will convert them to .txt over the weekend to avoid future issues.

**Comment by ChooJinHe** [comment]
Hi @1adrianb,

I have the latest Torch version. Really thank you for converting the landmarks to .txt

Best Regard,
Jin He
